org: 0xknon
app: bandai-cron
service: bandai-cron
frameworkVersion: '3'

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs18.x
  
plugins:
  - serverless-plugin-typescript

functions:
  auto-apply:
    handler: src/functions/handlers.autoApply
    timeout: 600 
    events:
      - schedule:
          rate: rate(12 hours)
          input:
            email: ykn121@gmail.com
      - schedule:
          rate: rate(12 hours)
          input:
            email: kwanmatthew20@gmail.com
      - schedule:
          rate: rate(12 hours)
          input:
            email: yumatthew497@gmail.com
      - schedule:
          rate: rate(12 hours)
          input:
            email: nokmatthew78@gmail.com
      - schedule:
          rate: rate(12 hours)
          input:
            email: milkyu92@gmail.com
      - schedule:
          rate: rate(12 hours)
          input:
            email: milkkwan880@gmail.com
      - schedule:
          rate: rate(12 hours)
          input:
            email: milknok4@gmail.com
      - schedule:
          rate: rate(12 hours)
          input:
            email: pigyu349@gmail.com
      - schedule:
          rate: rate(12 hours)
          input:
            email: pigkwan881@gmail.com
  report:
    handler: src/functions/handlers.report
    timeout: 600 
    events:
      - schedule: rate(12 hours)
  # rateHandler:
  #   handler: index.run
  #   events:
  #     # Invoke Lambda function every minute
  #     - schedule: rate(1 minute)
  # cronHandler:
  #   handler: index.run
  #   events:
  #     # Invoke Lambda function every 2nd minute from Mon-Fri
  #     - schedule: cron(0/2 * ? * MON-FRI *)
