org: 0xknon
app: knyu-serverless
service: knyu-serverless
frameworkVersion: "3"

provider:
  name: aws
  region: ap-southeast-1
  runtime: nodejs18.x

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  # - serverless-bundle
  - serverless-plugin-optimize
  - serverless-offline

functions:
  aavegotchi-pet:
    handler: src/functions/web3/handlers.autoPet
    timeout: 600
    events:
      - schedule:
          rate: rate(45 minutes)
  # auto-apply:
  #   handler: src/functions/handlers.autoApply
  #   timeout: 600
  #   events:
  #     - schedule:
  #         rate: cron(0 0 ? * * *)
  #         input:
  #           email: ykn121@gmail.com
  #     - schedule:
  #         rate: cron(0 0 ? * * *)
  #         input:
  #           email: knyutcg@gmail.com

  # report:
  #   handler: src/functions/handlers.report
  #   timeout: 600
  #   events:
  #     - schedule: cron(0 0 ? * * *)
  # rateHandler:
  #   handler: index.run
  #   events:
  #     # Invoke Lambda function every minute
  #     - schedule: rate(1 minute)
  # cronHandler:
  #   handler: index.run
  #   events:
  #     # Invoke Lambda function every 2nd minute from Mon-Fri
  #     - schedule: cron(0 0 ? * * *)
